### PR TITLE
F1 2019 Support

### PR DESCRIPTION
**Pull request by jonybur**
**This is still a work in progress**

Enables support for 2019 specs, by getting the game version from the header, and then deciding the strategy to parse each package (following 2018 or 2019 specs).

Adding support for all the new 2019 specs (as documented [here](https://forums.codemasters.com/topic/38920-f1-2019-udp-specification/))

Current changes:
> PacketHeader: Small changes
> CarMotionData: No changes
> PacketMotionData: No changes
> LapDataParser: No changes
> PacketLapDataParser: No changes
> PacketEventData: Adds EventDataDetails packet support
> PacketParticipantsData: Some changes
> CarSetupsData: No changes
> CarTelemetryData: Adds driving surface, change some values from int to float

### CODE REVIEW

**Comment by codegefluester** [comment]
Nice one! Are you going to update the driver + team list later on? https://forums.codemasters.com/topic/38920-f1-2019-udp-specification/?do=findComment&comment=434628

**Comment by jonybur** [comment]
Yeah I will see to add the constants. I am not sure if all of the constants will be out with this upcoming release (Im just aiming towards F1 2019 support, no constants needed) but I will eventually see that everything is added.

**Comment by codegefluester** [comment]
Happy to jump in and add them if you want?

**Comment by jonybur** [comment]
Of course! Please feel free to collaborate. Just branch from `0.1.8` so you have the latest changes. Thank you!

**Comment by jonybur** [comment]
@codegefluester I just added the F1 2019 constants, they're available starting from version 0.1.10

**Pull request merged**
