### PR TITLE
Add uint64 support for the session id

### PR DESCRIPTION
**Pull request by DerkJanSpeelman**
# Add uint64 support for the missing session id

I wanted to fetch the `m_sessionUID` inside the `PacketHeader` (sent inside every message). I found out there wasn't `uint64` support with `TypeScript 3.1.0` and the included `binary-parser` (version 1.3.2). So, I upgraded these packages. And everything seems to be working fine.

I'm also running on a newer version of Node (Latest Current Version 13.8.0). Thereby, it added a few version changes to the `package-lock.json`. But it should run fine from version 12 onwards:

`The methods readBigInt64BE, readBigInt64BE, readBigInt64BE, readBigInt64BE are not avilable in your version of nodejs: v10.19.0, you must use v12 or greater`

### I added `m_sessionUID` to the `PacketHeader`

In `src\parsers\packets\PacketHeaderParser.ts:18`, I added the sessionUID. We might want to change this `uint64` to a `uint64le`

### `class` is extending a `namespace`

I also found a bug the `F1TelemetryClient` class. This class extends the `EventEmitter` namespace, not the class. Just a small fix.

### `PacketSessionData`

I added the `m_formula` in the `PacketSessionData` interface. The `PacketSessionData` with the `PacketHeader` included now looks like this:

PacketSessionData

Note: check the `m_sessionUID` and `formula` attributes. And `m_pitSpeedLimit` is just the end of the screenshot, the regular data is still there ofcourse.

### CODE REVIEW

**Comment by jonybur** [comment]
Hi @DerkJanSpeelman thank you for your PR. This looks good! Can you please check out the tests (update them if necessary) so I can merge your changes? Thank you

**Comment by DerkJanSpeelman** [comment]
> Hi @DerkJanSpeelman thank you for your PR. This looks good! Can you please check out the tests (update them if necessary) so I can merge your changes? Thank you

I'd love to, but the Travis CI is setup with Node v10.19.0. Therefore:

`The methods readBigInt64BE, readBigInt64BE, readBigInt64BE, readBigInt64BE are not avilable in your version of nodejs: v10.19.0, you must use v12 or greater`

**Comment by jonybur** [comment]
@DerkJanSpeelman merged 👍

**Comment by jonybur** [comment]
@DerkJanSpeelman I had to revert this PR due because Travis running node 8, 10 wasn't the only problem: the tests are failing to check the value of `m_sessionUID`. The mocks folder possess a parsed version of all the packages, which do not include a value of `m_sessionUID`. Given that the value m_sessionUID is a bigint, we need to set the tsconfig to target ESNext and make the mocks in .ts  format (instead of .json). After that is done then this will be ready to merging 👍

**Pull request merged**
